# Generated by Django 3.1.7 on 2021-03-14 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_form', models.CharField(max_length=5)),
                ('institution', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('opac_domain', models.CharField(max_length=200)),
                ('resource_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=1000)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('edition', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('source_bib_id', models.IntegerField()),
                ('source_resource_id', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 6, 38, 44, 273563))),
                ('updated_at', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cat_backend.source')),
            ],
        ),
    ]
