# Generated by Django 3.1.7 on 2021-03-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='source_resource_id',
            new_name='source_control_id',
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 13, 12, 10, 228612)),
        ),
        migrations.RemoveField(
            model_name='record',
            name='source',
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.ManyToManyField(to='cat_backend.Source'),
        ),
    ]
